/*
 * cgenpre.h - OS/2 prelude prepended to release\cargen.c (the
 * sc-generated car.c template) before compilation.  The template only
 * includes <som.h> and "car.h"; car.h references PSZ/CDATE/LONG/etc.
 * without pulling os2.h itself, so the types must come from here.
 * Mirrors the C_ih passthru in idl\car.idl.
 */

#define INCL_WIN
#define INCL_DOS
#define INCL_GPIBITMAPS
#define INCL_DOSERRORS
#include <os2.h>

#define INCL_WPCLASS
#define INCL_WPFOLDER

#include <pmwp.h>
#include <pmstddlg.h>
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_car_Source
#define SOM_Module_car_Source
#endif
#define Car_Class_Source
#define M_Car_Class_Source

#include "car.ih"


/*
 * METHOD: QueryBrakes
 *    *   Query state of car's brakes.
 *    * RETURN:
 *    *   TRUE           Brake is on
 *    *   FALSE          Brake is off
 */

SOM_Scope BOOL  SOMLINK car_QueryBrakes(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_QueryBrakes");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: SetBrakes - put on the brakes
 */

SOM_Scope void  SOMLINK car_SetBrakes(Car *somSelf, BOOL fBrake)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_SetBrakes");

}

/*
 * METHOD: QueryDuration - query duration of horn beep
 */

SOM_Scope ULONG  SOMLINK car_QueryDuration(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_QueryDuration");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: SetDuration - set duration of horn beep
 */

SOM_Scope void  SOMLINK car_SetDuration(Car *somSelf, ULONG ulDuration)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_SetDuration");

}

/*
 * METHOD: QueryHighTone - query high frequency of horn
 */

SOM_Scope ULONG  SOMLINK car_QueryHighTone(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_QueryHighTone");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: SetHighTone - set high frequency of horn
 */

SOM_Scope void  SOMLINK car_SetHighTone(Car *somSelf, ULONG ulTone)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_SetHighTone");

}

/*
 * METHOD: QueryLowTone - query low frequency of horn
 */

SOM_Scope ULONG  SOMLINK car_QueryLowTone(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_QueryLowTone");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: SetLowTone - set low frequency of horn
 */

SOM_Scope void  SOMLINK car_SetLowTone(Car *somSelf, ULONG ulTone)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_SetLowTone");

}

/*
 * METHOD: QuerySpeed - query speed of car
 */

SOM_Scope ULONG  SOMLINK car_QuerySpeed(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_QuerySpeed");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: SetSpeed - set speed of car
 */

SOM_Scope void  SOMLINK car_SetSpeed(Car *somSelf, ULONG ulSpeed)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_SetSpeed");

}

/*
 * METHOD: BeepHorn - beep the car's horn.
 *    * RETURN: TRUE successful, FALSE unsuccessful
 */

SOM_Scope BOOL  SOMLINK car_BeepHorn(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_BeepHorn");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: AddDashboardPage - add the dashboard page to the settings
 *    * notebook.  Returns the inserted page id, or 0 on failure.
 *    * Override to replace/remove the dashboard page in descendants;
 *    * such overrides usually do not call the parent.
 */

SOM_Scope ULONG  SOMLINK car_AddDashboardPage(Car *somSelf, HWND hwndNotebook)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_AddDashboardPage");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: AddHornBeepPage - add the horn beep page to the settings
 *    * notebook.  Same return/override conventions as AddDashboardPage.
 */

SOM_Scope ULONG  SOMLINK car_AddHornBeepPage(Car *somSelf, HWND hwndNotebook)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_AddHornBeepPage");

    /* Return statement to be customized: */
    return;
}

/*
 * METHOD: TrapTest - demonstrates the sample's exception handling
 *    * by deliberately causing an access violation.
 */

SOM_Scope void  SOMLINK car_TrapTest(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_TrapTest");

}

SOM_Scope void  SOMLINK car_wpInitData(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpInitData");

    Car_parent_WPDataFile_wpInitData(somSelf);
}

SOM_Scope void  SOMLINK car_wpUnInitData(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpUnInitData");

    Car_parent_WPDataFile_wpUnInitData(somSelf);
}

SOM_Scope BOOL  SOMLINK car_wpSaveState(Car *somSelf)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpSaveState");

    return (Car_parent_WPDataFile_wpSaveState(somSelf));
}

SOM_Scope BOOL  SOMLINK car_wpRestoreState(Car *somSelf, ULONG ulReserved)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpRestoreState");

    return (Car_parent_WPDataFile_wpRestoreState(somSelf, ulReserved));
}

SOM_Scope BOOL  SOMLINK car_wpAddSettingsPages(Car *somSelf, 
                                               HWND hwndNotebook)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpAddSettingsPages");

    return (Car_parent_WPDataFile_wpAddSettingsPages(somSelf, 
                                                     hwndNotebook));
}

SOM_Scope ULONG  SOMLINK car_wpFilterPopupMenu(Car *somSelf, 
                                               ULONG ulFlags, 
                                               HWND hwndCnr, 
                                               BOOL fMultiSelect)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpFilterPopupMenu");

    return (Car_parent_WPDataFile_wpFilterPopupMenu(somSelf, 
                                                    ulFlags, 
                                                    hwndCnr, 
                                                    fMultiSelect));
}

SOM_Scope BOOL  SOMLINK car_wpModifyPopupMenu(Car *somSelf, HWND hwndMenu, 
                                              HWND hwndCnr, ULONG iPosition)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpModifyPopupMenu");

    return (Car_parent_WPDataFile_wpModifyPopupMenu(somSelf, 
                                                    hwndMenu, 
                                                    hwndCnr, 
                                                    iPosition));
}

SOM_Scope BOOL  SOMLINK car_wpMenuItemSelected(Car *somSelf, 
                                               HWND hwndFrame, 
                                               ULONG ulMenuId)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpMenuItemSelected");

    return (Car_parent_WPDataFile_wpMenuItemSelected(somSelf, 
                                                     hwndFrame, 
                                                     ulMenuId));
}

SOM_Scope BOOL  SOMLINK car_wpMenuItemHelpSelected(Car *somSelf, 
                                                   ULONG MenuId)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpMenuItemHelpSelected");

    return (Car_parent_WPDataFile_wpMenuItemHelpSelected(somSelf, 
                                                         MenuId));
}

SOM_Scope ULONG  SOMLINK car_wpQueryDetailsData(Car *somSelf, 
                                                PVOID* ppDetailsData, 
                                                PULONG pcp)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpQueryDetailsData");

    return (Car_parent_WPDataFile_wpQueryDetailsData(somSelf, 
                                                     ppDetailsData, 
                                                     pcp));
}

SOM_Scope HWND  SOMLINK car_wpOpen(Car *somSelf, HWND hwndCnr, 
                                   ULONG ulView, ULONG param)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpOpen");

    return (Car_parent_WPDataFile_wpOpen(somSelf, hwndCnr, ulView, 
                                         param));
}

SOM_Scope BOOL  SOMLINK car_wpSetup(Car *somSelf, PSZ pszSetupString)
{
    CarData *somThis = CarGetData(somSelf);
    CarMethodDebug("Car","car_wpSetup");

    return (Car_parent_WPDataFile_wpSetup(somSelf, pszSetupString));
}


/*
 * METHOD: clsQueryModuleHandle
 *    *   Returns the module handle of this class' DLL.  On first call,
 *    *   DosQueryModuleHandle resolves the registered pathname.
 *    * RETURN: 0 unsuccessful, non-zero module handle
 */

SOM_Scope HMODULE  SOMLINK carM_clsQueryModuleHandle(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_clsQueryModuleHandle");

    /* Return statement to be customized: */
    return;
}

SOM_Scope void  SOMLINK carM_wpclsInitData(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsInitData");

    M_Car_parent_M_WPDataFile_wpclsInitData(somSelf);
}

SOM_Scope void  SOMLINK carM_wpclsUnInitData(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsUnInitData");

    M_Car_parent_M_WPDataFile_wpclsUnInitData(somSelf);
}

SOM_Scope PSZ  SOMLINK carM_wpclsQueryTitle(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryTitle");

    return (M_Car_parent_M_WPDataFile_wpclsQueryTitle(somSelf));
}

SOM_Scope ULONG  SOMLINK carM_wpclsQueryIconData(M_Car *somSelf, 
                                                 PICONINFO pIconInfo)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryIconData");

    return (M_Car_parent_M_WPDataFile_wpclsQueryIconData(somSelf, 
                                                         pIconInfo));
}

SOM_Scope BOOL  SOMLINK carM_wpclsQueryDefaultHelp(M_Car *somSelf, 
                                                   PULONG pHelpPanelId, 
                                                   PSZ pszHelpLibrary)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryDefaultHelp");

    return (M_Car_parent_M_WPDataFile_wpclsQueryDefaultHelp(somSelf, 
                                                            pHelpPanelId, 
                                                            pszHelpLibrary));
}

SOM_Scope ULONG  SOMLINK carM_wpclsQueryDefaultView(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryDefaultView");

    return (M_Car_parent_M_WPDataFile_wpclsQueryDefaultView(somSelf));
}

SOM_Scope ULONG  SOMLINK carM_wpclsQueryDetailsInfo(M_Car *somSelf, 
                                                    PCLASSFIELDINFO* ppClassFieldInfo, 
                                                    PULONG pSize)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryDetailsInfo");

    return (M_Car_parent_M_WPDataFile_wpclsQueryDetailsInfo(somSelf, 
                                                            ppClassFieldInfo, 
                                                            pSize));
}

SOM_Scope PCLASSDETAILS  SOMLINK carM_wpclsQueryDetails(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryDetails");

    return (M_Car_parent_M_WPDataFile_wpclsQueryDetails(somSelf));
}

SOM_Scope PSZ  SOMLINK carM_wpclsQueryInstanceFilter(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryInstanceFilter");

    return (M_Car_parent_M_WPDataFile_wpclsQueryInstanceFilter(somSelf));
}

SOM_Scope ULONG  SOMLINK carM_wpclsQueryStyle(M_Car *somSelf)
{
    /* M_CarData *somThis = M_CarGetData(somSelf); */
    M_CarMethodDebug("M_Car","carM_wpclsQueryStyle");

    return (M_Car_parent_M_WPDataFile_wpclsQueryStyle(somSelf));
}

